id = "MonetinaThemes"
name = "Monetina Themes"
schema_version = 1
version = "1.0.4"
authors = ["ElMonetina <gabrielebonipistolesi@gmail.com>"]
description = "Collection of themes I made and use"
repository = "https://github.com/ElMonetina/MonetinaTheme"
